[tox]
envlist =
    py{310,311,312,313}-django52,
    performance, warnings, isort, lint, dist,

[travis]
unignore_outcomes = true

[testenv]
commands = coverage run manage.py test --exclude-tag=perf {posargs}
envdir = {toxworkdir}/venvs/{envname}
setenv =
    PYTHONDONTWRITEBYTECODE=1
deps =
    coverage>=5.0
    django-crispy-forms>=2.0
    djangorestframework~=3.17.0
    django-filter
    django52: django~=5.2.0


[testenv:performance]
commands = python manage.py test --tag=perf {posargs}
deps =
    django
    djangorestframework
    django-filter

[testenv:warnings]
ignore_outcome = True
commands = python -Werror manage.py test --exclude-tag=perf {posargs}
deps =
    django
    djangorestframework
    django-filter

[testenv:isort]
commands = isort --check-only rest_framework_filters tests {posargs:--diff}
deps = isort

[testenv:lint]
commands = flake8 rest_framework_filters tests {posargs}
deps =
    flake8
    darglint

    flake8-assertive
    flake8-bugbear
    flake8-builtins
    flake8-commas
    flake8-comprehensions
    flake8-docstrings

[testenv:dist]
commands =
    twine check dist/*
    python manage.py test --no-pkgroot --exclude-tag=perf {posargs}
deps =
    django
    djangorestframework
    django-filter
    django-crispy-forms>=2.0
    readme_renderer
    twine
